### ISSUE TITLE
Summer CYOA Meta Issue

### ISSUE THREAD

**Issue by JasonLin43212** [dhmit/democracy_africa#101]
This meta issue will contain issues for the summer term for CYOA.
[Link to CYOA text](https://docs.google.com/document/d/1gTZ_Sk_Wz4dYxiKfTVKSn9aZV6cKTnHBRUZGYimwpr8/edit)

- [x] When you click on "Agree; you want to participate in the sit-in!", the question text on top does not change.
- [x] Story needs to be smoothed out #104 
- [x] Missing images for some stages #105
- [x] Ending Screen Improvements #106
- [x] Abstract out the content so it can be reused #107 

Extra Stuff:
- [x] Grammer Check #121
