### ISSUE TITLE
Campaign Game Summer Term Meta Issue

### ISSUE THREAD

**Issue by JasonLin43212** [dhmit/democracy_africa#108]
Meta issue for Summer term of DH for Campaign Game

- [x] Final screen Improvements #109 
- [x] Responsive issues #110 
- [x] Priority Points Clarification #111
- [x] Feedback Improvements #112
- [x] Better “storyline” #113

- [x] Feedback improvements again #122 
- [x] Priority Point Improvement again #126 

- [x] Final Styles #128

Extra Stuff:
- [x] Try Again Button in final screen off center (Fixed in responsive issues)
- [x] Have a way of clicking on the country after you have clicked on a province. Maybe we can click outside of the country.
