### ISSUE TITLE
Meta Issue for Map Quiz

### ISSUE THREAD

**Issue by bengao01** [dhmit/democracy_africa#11]
We are working on creating a quiz of all the countries in Africa. Features that we need to have implemented: 

- [x] Create a timer
  - [x] Start when the user starts submitting responses, and stop when time is up or user finishes
- [x] Visual feedback for correct/incorrect responses
- [x] Implement score tracking
  - [x] Don't count already submitted countries
- [x] Allow users to click on countries to input name
  - [x] Prevent users from resubmitting for countries already attempted
- [x] Fix button placement and timer/counter placement
  - Layout is not responsive
- [x] Grey out country names that have already been guessed correctly

**Comment by ryaanahmed** [comment]
Looks like this was all done by end of IAP! Thanks all. Closing.
