### ISSUE TITLE
Meta-Issue: Gamification of Democracy Visualization 

### ISSUE THREAD

**Issue by meesuekim** [dhmit/democracy_africa#44]
Minimum Viable Product:
- [x] Create and collaborate with other groups @opheeelia on the React component for the question
    - Have questions pop up on right side of the map
- [x] Figure out how to format the database (probably JSON)
- [x] Remove dropdown (for now) and shorten width of slide bar*
- [ ] Title and Intro Text
    - Instructions on how to play the game
    - Info on how the map works
- [x] Score tracker
    - Add points with every question answered correctly
    - Displays overall number of points gained out of total number of points possible 
- [ ] Visual Feedback:
    - Green for correct
    - Red for incorrect and then highlight correct answer
- [ ] Hover Feature:
    - Displays country name and democracy index
- [x] Scale map size to fit nicely in window when screen is resized/ on mobile

Stretch Goals:
- [ ] Hard/Easy mode
    - This can just be based on whether user knows the map of Africa by heart
    - Hover feature would no longer display country name for hard mode
- [ ] Different answer formats
    - Country shapes instead of names
    - Dropdown Menu
    - Textbox
- [ ] Click on year in question box --> moves the slider to appropriate in response to click
- [ ] *Different Democracy Scores
    - This would require bringing back the dropdown menu
- [ ] Answer box popup
    - Include "Correct!"
    - Elaborate on correct answer, fun facts, etc.
    - Display photo

**Comment by meesuekim** [comment]
Score tracker and hover feature can be factored out
- other groups will be using these
- score tracker has already been done for the map quiz

**Comment by ryaanahmed** [comment]
great! did you happen to get any pictures of your whiteboard sketches? would be great to include here for context if possible.

**Comment by Crista2019** [comment]
Our whiteboard sketches:
![IMG_20200214_150111424](https://user-images.githubusercontent.com/13463219/75612822-45a2b580-5af5-11ea-9ac5-489eec0d051e.jpg)
