### ISSUE TITLE
Create your own story Meta-Issue

### ISSUE THREAD

**Issue by Mayowa99** [dhmit/democracy_africa#45]
- [x] Hard code and write up the input data structure
  - [x] Dictionary --> {Stage: (option_key, option_key2), option_key: (option1, option2)}
- [x] Intro Page:
  - [x] Consists of text explaining the player's situation and an image, start button
- [ ] Options pages
  - [x] Components for the options
    - [x] Contain a link to another page
    - [ ] An image representing the choice
    - [ ] Text describing the exact details of the choice
    - [x] Accept choice button
      - [x] Send player to another page 
  - [x] ‘What you did so far’ component
    - [x] Keep track of the options that user has selected thus far
  - [ ] Add background images and little descriptors of the world at that stage
- [ ] Result page
  - [ ] Display a visual on how your success rate dropped as you progressed
  - [ ] More info tab that links to more about the country

Stretch goal:
- [ ] Different situations pop up depending on budget settings

![IMG_4637](https://user-images.githubusercontent.com/47461505/74778357-65221e80-5269-11ea-93e9-58e1a26b2d68.jpg)

**Comment by ryaanahmed** [comment]
looks good! did any of you happen to get a picture of your whiteboard sketches? would be good to post those here, too, for context.

**Comment by Mayowa99** [comment]
I did, I’ll upload it now

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by maoivy** [comment]
Started making React skeleton (will update with link to issue)
