### ISSUE TITLE
Meta Issue for Ethnolinguistic Map

### ISSUE THREAD

**Issue by wilke0818** [dhmit/democracy_africa#46]
We want to create an Ethnolinguistic Map that will allow the user to manipulate different overlays over the political boundaries map of Africa in order for them to explore how different ethnic groups, religious groups, and linguistic groups may all live in a single country causing possible political conflicts. 

GeoJSON of Ethic Politically Relevant Groups: https://icr.ethz.ch/data/epr/geoepr/GeoEPR-2019.geojson

Frontend:
- [ ] Create map of Africa using GeoJSON that HeatMap group used #47 
- [ ] Add/Learn how to add overlays on top of the SVG map #47
- [ ] Create a dropdown menu to select between different overlay datasets #48
- [ ] Create a slider that will allow us to make the political boundaries more transparent (work with the democracy visualization group to reuse theirs) #48
- [ ] Create questions that make the user think about the affects of political borders interfering with ethnic and linguistic borders (work with the democracy visualization group as they are also planning on creating React components for this).

Backend:
- [ ] Create datasets for the SVG paths that will need to be used for the overlays (talk with @ryaanahmed about which datasets and have him add them) #49
- [ ] Add to views.py so that we can send the paths to the frontend for different datasets based on the selected option from the dropdown menu #49
![86345355_575978482984165_4378176733967286272_n](https://user-images.githubusercontent.com/39885245/74569567-af915b80-4f48-11ea-89f8-9f11c4112848.jpg)
