### ISSUE TITLE
Meta Issue for Campaign Simulation

### ISSUE THREAD

**Issue by bengao01** [dhmit/democracy_africa#50]
We want to create a campaign simulation to educate users on the challenges associated with finding a good way to balance resources and to appeal to a broader group of people. They will be able to choose their priority on a set number of topics and see the number of people that would have voted for them, based on their priorities.

**Frontend**
- [x]  Create the visualization of individual districts for each country 
- [ ]  When the user clicks on a district, show information about the average priority data for each district #84 
- [x]  Have a selection of topics (around 10) and allow the user to pick priority numbers for each topic
- [x]  Develop a model that takes in the user-assigned priority scores to determine the number of votes received

- Less people. More realistic models of people?
- "Prioritizing what citizens want... you are running for leadership in this country."
- "You just started your campaign and we want you to set out your policies so that we can poll the people to get the initial reaction."
- "You can prioritize more things. If you want to prioritize other things, you need to de-prioritize others"
- "we can do two more polls before elections. This is the final policies that people will see in the election"
- "people say i voted in results page b/c of the candidate's stance on ..."
After Meeting with Michael:
- [x] Overview page with intro explaining how to play the game. #71 
    - [ ] Clarify things like (1 is the lowest score) and you need to click on outside to look a full country score
- [ ] Total supporters of a country should always be visible. #71 
- [ ] Hints on what people might want. #69 
- [ ] Make radio buttons bigger. #69 
- [x] Highlight provinces that are clicked on. #70 

Evan's Comments (based on what he said below):
- [ ] Hover over a province to get information or hints on what that population may want.
- [x] Submit button to get tally of overall support (like a final test)
- [ ] Different shades of support for each province

Integrating Budget Simulator:
- [x] Population visualizer for each province #79 

**Backend**
- [x]  Write an API endpoint to access the Afrobarometer survey data #53 
- [x]  Write a method that stores all the relevant data we need into an object
- [x] Create a model for the citizens of a district

**Review**
-  Change text in beginning to match game more.
- Is it color coded??
- What do they want (fixed using the data at beginning)
- Wasn't clear that you click on provinces to select them
- Skipped feedback???
- Tell you what they really have, what they would like to have, what they don't care about
- Something wrong with reseting speech proposals after each game
- Couldn't tell when you were allowed to switch to. Color the buttons red that you can't switch to
- You are going to try out a campaign platform. You can pick lead themes? and secondary themes to test out. Maybe have a sentence that is pretty specific that might go into a campaign speech so that it feel like a campaigned. Goal is to help the user who appreciates the translation to text. Need more scaffolding for person, maybe stick people - Evan

![IMG_20200214_171142](https://user-images.githubusercontent.com/55002595/74574022-50cfe000-4f50-11ea-890f-eba07f7d0036.jpg)

![IMG_20200214_164656](https://user-images.githubusercontent.com/55002595/74574027-54636700-4f50-11ea-9481-8fd9629fee3c.jpg)

**Comment by ryaanahmed** [comment]
> Create a model for the citizens of a district

Seems to me that much of this is already done by the existing budget simulator code. Ask @montsegarza @wilke0818 or @amy-lei who worked on that during IAP if you need help navigating what's there. There's a `Citizen` and `Population` class in the `models.py`. You'll probably want your afrobarometer loading code to tie into that existing code.

**Comment by evanlieb** [comment]
I had not seen the comments above when i wrote my comments, but VERY SIMILAR: Campaign game – 
Cool – needs some guidance about what is a “priority point” and how they get allocated. And some good STORIES.

Is it possible that I could hover over a province and learn some information about the population in order to make my choices? Maybe change the colors of the provinces as my support base changes based on my policy choices?

Might be nice to have to press “submit” to see my final overall tally of how many people support me at the end, telling me my promises, what I said I would do; and what I was forced to de-prioritize. 

But the basic tool is cool. nice
