### ISSUE TITLE
Visualizing Trust -- Meta Issue 

### ISSUE THREAD

**Issue by amy-lei** [dhmit/democracy_africa#51]
The purpose of the visualizing trust game is to help the users understand the consequences of the slave trade on interpersonal trust by examining how changes in slave exports in a district impact current trust levels. The user must optimize trust levels given resource constraints. 

- [ ] Intro page
  - [ ] explain the concepts behind the game (history talk & instructions)
  - [x] next button

- [ ] Map of present day / start game button 

- [ ] Frontend of Game 
  - [x] GET data once mounted 
  - [ ]  Map component that displays trust levels/slave exports
    - [x] Use country map for now 
    - [ ] On hover, displays district info component
    - [ ] On click, changes slider component
    - [ ] Dynamically colored based on trust level/slave exports (taken from democracy heat map)
  - [ ] AggregateData component that displays min, max, mean, median
  - [ ] Slider component 
    - [ ] max value capped at initial conditions 
    - [ ] data displayed changes with click 
    - [ ] on change, update number for that district and constraint counter 
  - [ ] DistrictInfo component 
  - [ ] Submit/Reset buttons
    - [x] Display AggregateData component for Interpersonal trust on submit 
    - [ ] Change values to initial export/trust level on reset
  - [ ] Constraint 
  - [ ] Fake calculations to associate trust level with slave exports (for testing code)
  - [x] set up view
- [ ] Backend of Game
  - [ ] Fakeeee data 
    - [ ] given a json file, restructure it to match `{'name':'', 'export':0,'trust':0,}`
    - [ ] fake data for country not district for now 
  - [ ] API endpoint for getting data

![image](https://user-images.githubusercontent.com/42757189/74574854-fdab5c80-4f52-11ea-9293-377a3d2d15a3.png)
![image](https://user-images.githubusercontent.com/42757189/74574860-0308a700-4f53-11ea-8dd6-182aa896ac56.png)
