### ISSUE TITLE
Meta Issue for Identity Activation Game

### ISSUE THREAD

**Issue by montsegarza** [dhmit/democracy_africa#59]
This is a revamp of Issue #46. It is an entirely different project, but with the same pedagogical goals.

We want to create a game where the user acts as a politician attempting to gain support by activating citizens' numerous identities. For this sprint, we will use Kenya and its districts as a case study.

Data Collection:
- [x] Choose individual characteristics/identities to represent in data
- [x] Find Kenya district data for chosen identities

Backend:
- [ ] Make data parsing function to rewrite data in a readable format (Python dictionary)
- [ ] Make probabilistic models on chosen data 
- [ ] Make people models with characteristics based on above probabilities
- [ ] Find a way to combine the budget simulation models with these models

Frontend:
- [ ] Activation toggle interface
- [ ] People dot interface for all of Kenya and each district
- [ ] Dots changing color if identity activated

![87075771_2228760514095451_9171854501139709952_n](https://user-images.githubusercontent.com/47461589/75070687-c3e1d500-54c1-11ea-9a53-4933fec6b9c5.jpg)

**Comment by montsegarza** [comment]
-Chosen data categories: language, religion, occupation, ethnicity
-Csv files (from Afrobarometer Kenyan district data) added to "ethno_linguistic_data"  branch
