### ISSUE TITLE
CYOA Frontend Tracking Issue

### ISSUE THREAD

**Issue by Dylan-Weber** [dhmit/democracy_africa#80]
- General
    - [x] Make buttons less basic
    - [x] Make buttons look good
    - [ ] Format paragraphs so they are less of a wall of text
    - [ ] Add disclaimer telling them not to click the previous/next buttons
    - [ ] Consider responsiveness
- Stage View
    - [x] Add images
    - [ ] Set up icons/images for the choices
- End View
    - [ ] Make the end view show meaningful data (chart/unlikely vs likely)

**Comment by ryaanahmed** [comment]
Can we add images on the stage views, as well?

**Comment by Dylan-Weber** [comment]
Yup, added.

**Comment by ryaanahmed** [comment]
Looking really great, all! One comment -- the bits at the end still look like buttons, and I got a bit confused bc I couldn't click them:

<img width="592" alt="Screen Shot 2020-04-22 at 3 17 08 PM" src="https://user-images.githubusercontent.com/691117/80024107-8b07b180-84ac-11ea-8b58-56c1caa2712b.png">
